/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Medico;
import model.Endereco;
import model.Contato;
import controller.MedicoController;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import utils.ErroConectarException;
import utils.ErroDAOException;
import utils.ErroNegocioException;

/**
 *
 * @author MARCOS
 */
public class FrmCadMedico extends javax.swing.JFrame {

    private Medico medico;
    private MedicoController controlMedico;
    private String[] messages;

    public FrmCadMedico() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        controlMedico = MedicoController.getInstance();
    }

    private void preencher() {
        medico = new Medico();
        medico.setNome(jTNome.getText().trim());
        Endereco endereco = new Endereco();
        endereco.setRua(jTRua.getText().trim());
        endereco.setCidade(jTCidade.getText().trim());
        endereco.setBairro(jTBairro.getText().trim());
        endereco.setCep(jFCEP.getText().trim());
        endereco.setComplemento(jTComplemento.getText().trim());
        endereco.setNumeroResidencia(jTNumeroResidencia.getText().trim());
        endereco.setUf(jComboUF.getSelectedItem().toString());
        medico.setEndereco(endereco);
        medico.setRg(jTRG.getText().trim());
        medico.setCpf(jFCPF.getText().trim());
        medico.setLogin(jTLogin.getText().trim());
        medico.setSenha(new String(jPSenha.getPassword()));
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            medico.setDataAdmissao(format.parse(format.format(new Date())));
            medico.setDataNascimento(format.parse(jFDataNascimento.getText().trim()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
        }
        medico.setSexo(jComboSexo.getSelectedItem().toString());
        medico.setIdade(Age.calculateAge(jFDataNascimento.getText().trim(), "dd/MM/yyyy"));

        Contato contato = new Contato();
        contato.setTelefone(jFTelefone.getText().trim());
        contato.setCelular(jFCelular.getText().trim());
        contato.setEmail(jTEmail.getText().trim());
        medico.setContato(contato);
    }

    private void limpar() {
        jTNome.setText("");
        jTRua.setText("");
        jTCidade.setText("");
        jTBairro.setText("");
        jTComplemento.setText("");
        jFCEP.setValue(null);
        jComboUF.setSelectedItem(0);
        jTNumeroResidencia.setText("");
        jTRG.setText("");
        jFCPF.setValue(null);
        jTLogin.setText("");
        jPSenha.setText("");
        jFDataNascimento.setValue(null);
        jComboSexo.setSelectedItem(0);
        jFCRM.setValue(null);
        jTSalario.setText("");
        jComboFuncao.setSelectedItem(0);
        jFTelefone.setValue(null);
        jFCelular.setValue(null);
        jTEmail.setText("");
        jTNome.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFCEP = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboUF = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTRG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFCPF = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTLogin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPSenha = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jFDataNascimento = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jFCRM = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jTSalario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboFuncao = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jFCelular = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTComplemento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTNumeroResidencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dados Cadastrais do Médico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 410, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        jTNome.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 620, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rua");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, -1));

        jTRua.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 620, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cidade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));

        jTCidade.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 260, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bairro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 60, -1));

        jTBairro.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 280, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CEP");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 20));

        try {
            jFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCEP.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jFCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UF");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, -1));

        jComboUF.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraná", "Pernambuco", "Piauí", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        getContentPane().add(jComboUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 130, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RG");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 30, -1));

        jTRG.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 110, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CPF");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 40, -1));

        try {
            jFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCPF.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 100, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Login");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, -1));

        jTLogin.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Senha");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, -1));

        jPSenha.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jPSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 220, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data de Nasc.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 100, -1));

        try {
            jFDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDataNascimento.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jFDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFDataNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jFDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 100, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CRM");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 40, 20));

        jFCRM.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jFCRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 120, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Salário R$");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, -1));

        jTSalario.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 50, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Função");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 30));

        jComboFuncao.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico", "Diretor", "Residente" }));
        getContentPane().add(jComboFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 160, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Telefone");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 70, -1));

        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefone.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jFTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 100, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Celular");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 60, -1));

        try {
            jFCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCelular.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jFCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 180, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("E-Mail");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, -1));

        jTEmail.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 610, -1));

        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 40));

        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 110, 40));

        jLabel21.setFont(new java.awt.Font("Lucida Calligraphy", 2, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("X");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 50, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Complemento");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jTComplemento.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 390, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nº de Residência");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jTNumeroResidencia.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        getContentPane().add(jTNumeroResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 60, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sexo");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, -1));

        jComboSexo.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Trans", "Homossexual", "Outros" }));
        getContentPane().add(jComboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back_add_medico.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFDataNascimentoActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTNome.getText().trim().equals("")) {
            messages = MessageView.requiredField("Nome");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTNome.requestFocus();
        } else if (jTRua.getText().trim().equals("")) {
            messages = MessageView.requiredField("Rua");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTRua.requestFocus();
        } else if (jTCidade.getText().trim().equals("")) {
            messages = MessageView.requiredField("Cidade");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTBairro.requestFocus();
        } else if (jTBairro.getText().trim().equals("")) {
            messages = MessageView.requiredField("Bairro");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTBairro.requestFocus();
        } else if (!jFCEP.isEditValid()) {
            messages = MessageView.requiredField("CEP");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jFCEP.requestFocus();
        } else if (jTComplemento.getText().trim().equals("")) {
            messages = MessageView.requiredField("Complemento");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTComplemento.requestFocus();
        } else if (jTNumeroResidencia.getText().trim().equals("")) {
            messages = MessageView.requiredField("Nº de Residência");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTNumeroResidencia.requestFocus();
        } else if (jTRG.getText().trim().equals("")) {
            messages = MessageView.requiredField("RG");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTRG.requestFocus();
        } else if (!jFCPF.isEditValid()) {
            messages = MessageView.requiredField("CPF");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jFCPF.requestFocus();
        } else if (jTLogin.getText().trim().equals("")) {
            messages = MessageView.requiredField("Login");
            JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
            jTLogin.requestFocus();
        } else {
            String senha = new String(jPSenha.getPassword());
            if (senha.trim().equals("")) {
                messages = MessageView.requiredField("Senha");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jPSenha.requestFocus();
            } else if (!jFDataNascimento.isEditValid()) {
                messages = MessageView.requiredField("Data de Nascimento");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jFDataNascimento.requestFocus();
            } else if (!jFCRM.isEditValid()) {
                messages = MessageView.requiredField("CRM");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jFCRM.requestFocus();
            } else if (jTSalario.getText().trim().equals("")) {
                messages = MessageView.requiredField("Salário");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jTSalario.requestFocus();
            } else if (!jFTelefone.isEditValid()) {
                messages = MessageView.requiredField("Telefone");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jFTelefone.requestFocus();
            } else if (!jFCelular.isEditValid()) {
                messages = MessageView.requiredField("Celular");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jFCelular.requestFocus();
            } else if (jTEmail.getText().trim().equals("")) {
                messages = MessageView.requiredField("E-Mail");
                JOptionPane.showMessageDialog(rootPane, messages[0], messages[1], JOptionPane.WARNING_MESSAGE);
                jTEmail.requestFocus();
            }else{
                preencher();
                try {
                    controlMedico.cadastrarMedico(medico);
                    JOptionPane.showMessageDialog(rootPane, "Os dados " + (medico.getSexo().equals("Masculino") ? "do Médico " : "da Médica ") + medico.getNome() + " foram cadastrados com sucesso no sistema.", (medico.getSexo().equals("Masculino") ? "Médico cadastrado com sucesso!" : "Médica cadastrada com sucesso!"), JOptionPane.INFORMATION_MESSAGE);
                    limpar();
                } catch (ErroDAOException | ErroConectarException | ErroNegocioException | SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                    limpar();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboFuncao;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JComboBox<String> jComboUF;
    private javax.swing.JFormattedTextField jFCEP;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFCRM;
    private javax.swing.JFormattedTextField jFCelular;
    private javax.swing.JFormattedTextField jFDataNascimento;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTLogin;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumeroResidencia;
    private javax.swing.JTextField jTRG;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTSalario;
    // End of variables declaration//GEN-END:variables
}
