/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Funcionario;
import model.Endereco;
import model.Contato;
import controller.FuncionarioController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import utils.ErroConectarException;
import utils.ErroDAOException;
import utils.ErroNegocioException;

/**
 *
 * @author MARCOS
 */
public class FrmCadFuncionario extends javax.swing.JFrame {

    private Funcionario funcionario;
    private FuncionarioController controlFuncionario;

    /**
     * Creates new form FrmCadFuncionario
     */
    public FrmCadFuncionario() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        controlFuncionario = FuncionarioController.getCurrentInstance();
    }

    private void limpar() {
        jTNome.setText("");
        jTRua.setText("");
        jTCidade.setText("");
        jTBairro.setText("");
        jFCEP.setValue(null);
        jTNumeroResidencia.setText("");
        jTComplemento.setText("");
        jComboUF.setSelectedItem(0);
        jTRG.setText("");
        jFCPF.setValue(null);
        jTLogin.setText("");
        jPSenha.setText("");
        jFDataNascimento.setValue(null);
        jTSalario.setText("");
        jComboFuncao.setSelectedItem(0);
        jComboSexo.setSelectedItem(0);
        jFTelefone.setValue(null);
        jFCelular.setValue(null);
        jTEmail.setText("");
        jTNome.requestFocus();

    }

    private void preencher() {
        funcionario = new Funcionario();
        funcionario.setNome(jTNome.getText().trim());
        Endereco endereco = new Endereco();
        endereco.setRua(jTRua.getText().trim());
        endereco.setCidade(jTCidade.getText().trim());
        endereco.setBairro(jTBairro.getText().trim());
        endereco.setCep(jFCEP.getText().trim());
        endereco.setNumeroResidencia(jTNumeroResidencia.getText().trim());
        endereco.setUf(jComboUF.getSelectedItem().toString());
        endereco.setComplemento(jTComplemento.getText().trim());
        funcionario.setEndereco(endereco);
        funcionario.setRg(jTRG.getText().trim());
        funcionario.setCpf(jFCPF.getText().trim());
        funcionario.setLogin(jTLogin.getText().trim());
        funcionario.setSenha(new String(jPSenha.getPassword()));
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            funcionario.setDataAdmissao(format.parse(format.format(new Date())));
            funcionario.setDataNascimento(format.parse(jFDataNascimento.getText().trim()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Data Inválida!", JOptionPane.ERROR_MESSAGE);
        }
        funcionario.setSexo(jComboSexo.getSelectedItem().toString());
        funcionario.setIdade(Age.calculateAge(jFDataNascimento.getText().trim(), "dd/MM/yyyy"));
        funcionario.setSalario(Double.parseDouble(jTSalario.getText().trim()));
        funcionario.setFuncao(jComboFuncao.getSelectedItem().toString());
        Contato contato = new Contato();
        contato.setTelefone(jFTelefone.getText().trim());
        contato.setCelular(jFCelular.getText().trim());
        contato.setEmail(jTEmail.getText().trim());
        funcionario.setContato(contato);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTRua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFCEP = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTNumeroResidencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboUF = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTRG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFCPF = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTLogin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPSenha = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jFDataNascimento = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTSalario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboFuncao = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFCelular = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jBtnAlterar = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTComplemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel1.setText("Nome");

        jTNome.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel2.setText("Rua");

        jTRua.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel3.setText("Cidade");

        jTCidade.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel4.setText("Bairro");

        jTBairro.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel5.setText("CEP");

        try {
            jFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCEP.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 2, 12)); // NOI18N
        jLabel6.setText("Nº da Residência");

        jTNumeroResidencia.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel7.setText("UF");

        jComboUF.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        jComboUF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel8.setText("RG");

        jTRG.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel9.setText("CPF");

        try {
            jFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCPF.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel10.setText("Login");

        jTLogin.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel11.setText("Senha");

        jPSenha.setFont(new java.awt.Font("Lucida Handwriting", 2, 13)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel12.setText("Data de Nascimento");

        try {
            jFDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDataNascimento.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel13.setText("Salário R$");

        jTSalario.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel14.setText("Função");

        jComboFuncao.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Atendente" }));
        jComboFuncao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel15.setText("Sexo");

        jComboSexo.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N
        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Trans", "Homossexual", "Outros" }));
        jComboSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel16.setText("Telefone");

        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefone.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel17.setText("Celular");

        try {
            jFCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFCelular.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel18.setText("E-Mail");

        jTEmail.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        jBtnAlterar.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_db_add_3209 (1).png"))); // NOI18N
        jBtnAlterar.setText("Cadastrar");
        jBtnAlterar.setToolTipText("Cadastra os dados do Funcionário no sistema.");
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnFechar.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_10_61474.png"))); // NOI18N
        jBtnFechar.setText("Fechar");
        jBtnFechar.setToolTipText("Fecha a tela do formulário de cadastro do Funcionário.");
        jBtnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFecharActionPerformed(evt);
            }
        });

        jBtnLimpar.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jBtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_edit-clear_23227.png"))); // NOI18N
        jBtnLimpar.setText("Limpar");
        jBtnLimpar.setToolTipText("Limpa todos os campos do Formulário de cadastro.");
        jBtnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Open Sans", 2, 24)); // NOI18N
        jLabel19.setText("Dados Cadastrais do Funcionário");

        jLabel20.setFont(new java.awt.Font("Lucida Handwriting", 2, 12)); // NOI18N
        jLabel20.setText("Complemento");

        jTComplemento.setFont(new java.awt.Font("Lucida Calligraphy", 2, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(67, 67, 67)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboFuncao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTRG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jBtnLimpar)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jBtnFechar))
                                                        .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addComponent(jBtnAlterar, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                                        .addComponent(jTRua)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(293, 293, 293)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTComplemento))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(250, 250, 250)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(68, 86, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAlterar, jBtnFechar, jBtnLimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnLimpar)
                            .addComponent(jBtnFechar))))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAlterar, jBtnFechar, jBtnLimpar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (jTNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo Nome é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTNome.requestFocus();
        } else if (jTRua.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo Rua é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTRua.requestFocus();
            jTRua.requestFocus();
        } else if (jTBairro.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo Bairro é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTBairro.requestFocus();
        } else if (!jFCEP.isEditValid()) {
            JOptionPane.showMessageDialog(rootPane, "O Campo CEP é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jFCEP.requestFocus();
        } else if (jTNumeroResidencia.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo Nº da Residência é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTNumeroResidencia.requestFocus();
        } else if (jTRG.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo RG é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTRG.requestFocus();
        } else if (!jFCPF.isEditValid()) {
            JOptionPane.showMessageDialog(rootPane, "O Campo CPF é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jFCPF.requestFocus();
        } else if (jTLogin.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O Campo Login é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
            jTLogin.requestFocus();
        } else {
            String senha = new String(jPSenha.getPassword());
            if (senha.trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O Campo Senha é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jPSenha.requestFocus();
            } else if (!jFDataNascimento.isEditValid()) {
                JOptionPane.showMessageDialog(rootPane, "O Campo Data de Nascimento é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jFDataNascimento.requestFocus();
            } else if (jTSalario.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O Campo Salário é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jTSalario.requestFocus();
            } else if (!jFTelefone.isEditValid()) {
                JOptionPane.showMessageDialog(rootPane, "O Campo Telefone é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jFTelefone.requestFocus();
            } else if (!jFCelular.isEditValid()) {
                JOptionPane.showMessageDialog(rootPane, "O Campo Celular é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jFCelular.requestFocus();
            } else if (jTEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O Campo E-Mail é um campo obrigatório portanto não pode ficar vazio.", "Campo Obrigatório!", JOptionPane.WARNING_MESSAGE);
                jTEmail.requestFocus();
            } else {
                preencher();
                try {
                    controlFuncionario.cadastrarFuncionario(funcionario);
                    JOptionPane.showMessageDialog(rootPane, "Os dados " + (funcionario.getSexo().equals("Masculino") ? "do Funcionário " : "da Funcionária ") + funcionario.getNome() + " foram cadastrados com sucesso no Sistema!", (funcionario.getSexo().equals("Masculino")? "Funcionário cadastrado com sucesso" : "Funcionária cadastrada com sucesso."), JOptionPane.INFORMATION_MESSAGE);
                    limpar();
                } catch (ErroDAOException | ErroConectarException | ErroNegocioException | SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(), (ex instanceof ErroDAOException? "Erro de Query SQL!" : (ex instanceof ErroNegocioException? "Erro de Validação de Dados!" : "Erro ao conectar com o banco de dados!")), JOptionPane.ERROR_MESSAGE);
                    limpar();
                }
            }
        }


    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JComboBox<String> jComboFuncao;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JComboBox<String> jComboUF;
    private javax.swing.JFormattedTextField jFCEP;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFCelular;
    private javax.swing.JFormattedTextField jFDataNascimento;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTLogin;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumeroResidencia;
    private javax.swing.JTextField jTRG;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTSalario;
    // End of variables declaration//GEN-END:variables
}
